//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;
    
    public partial class ART : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ART()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int art_id { get; set; }
        private string _art1;
        public string art1
        {
            get => _art1;
            set => Set(ref _art1, value);
        }
        public string street { get; set; }
        public Nullable<int> street_n { get; set; }
        public Nullable<int> floor { get; set; }
        public string departament { get; set; }
        public Nullable<int> province_id { get; set; }
        public string city { get; set; }
        public Nullable<int> postal_code { get; set; }
        public Nullable<long> phone_n { get; set; }
    
        public virtual Provinces Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
