//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Banks : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banks()
        {
            this.Liquidation_fixed_datas = new HashSet<Liquidation_fixed_datas>();
        }

        public int bank_id { get; set; }
        private string _bank;
        public string bank
        {
            get => _bank;
            set => Set(ref _bank, value);
        }
        public string street { get; set; }
        public Nullable<int> street_n { get; set; }
        public Nullable<int> floor { get; set; }
        public string departament { get; set; }
        public Nullable<int> province_id { get; set; }
        public string city { get; set; }
        public Nullable<int> postal_code { get; set; }
        public Nullable<long> phone_n { get; set; }

        public virtual Provinces Provinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidation_fixed_datas> Liquidation_fixed_datas { get; set; }
    }
}