//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Categorys : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorys()
        {
            this.Employees = new HashSet<Employees>();
        }

        public int category_id { get; set; }
        private string _category;
        public string category
        {
            get => _category;
            set => Set(ref _category, value);
        }
        public string description { get; set; }
        public decimal basic_salary { get; set; }
        public Nullable<decimal> amount_extra_1 { get; set; }
        public Nullable<decimal> amount_extra_2 { get; set; }
        public Nullable<decimal> amount_extra_3 { get; set; }
        public Nullable<decimal> amount_extra_4 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
