//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using System;
    using System.Collections.Generic;

    public partial class Companys
    {
        public int company_id { get; set; }
        public string company { get; set; }
        public string street { get; set; }
        public int street_n { get; set; }
        public int province_id { get; set; }
        public string city { get; set; }
        public int postal_code { get; set; }
        public long cuit_n { get; set; }
        public long phone_n { get; set; }

        public virtual Provinces Provinces { get; set; }
    }
}
