//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Concepts : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concepts()
        {
            this.Employees = new HashSet<Employees>();
        }

        public int concept_id { get; set; }
        private int _sorted_concept_id;
        public int sorted_concept_id
        {
            get => _sorted_concept_id;
            set => Set(ref _sorted_concept_id, value);
        }
        private string _concept;
        public string concept
        {
            get => _concept;
            set => Set(ref _concept, value);
        }
        public int concept_type_id { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int formula_id { get; set; }
        public bool common { get; set; }
        public bool quantity_editable { get; set; }

        private Concept_types _concept_types;
        public virtual Concept_types Concept_types
        {
            get => _concept_types;
            set => Set(ref _concept_types, value);
        }
        public virtual Formulas Formulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }

    public partial class Concepts : ObservableObject
    {
        private bool _add;
        public bool add
        {
            get => _add;
            set => Set(ref _add, value);
        }
        private bool _edit;
        public bool edit
        {
            get => _edit;
            set => Set(ref _edit, value);
        }
        private bool _selected;
        public bool selected
        {
            get => _selected;
            set => Set(ref _selected, value);
        }

        public string fullconcept
        {
            get => sorted_concept_id.ToString() + " - " + concept;
        }

        private string _quantityn;
        public string quantityn
        {
            get => _quantityn;
            set => Set(ref _quantityn, value);
        }
        public decimal? quantitynedited { get; set; }

        private decimal? _r = null;
        public decimal? r
        {
            get => _r;
            set => Set(ref _r, value);
        }
        private decimal? _nr = null;
        public decimal? nr
        {
            get => _nr;
            set => Set(ref _nr, value);
        }
        private decimal? _d = null;
        public decimal? d
        {
            get => _d;
            set => Set(ref _d, value);
        }
    }
}
