//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using System;
    using System.Collections.Generic;

    public partial class Employees_liquidated_concepts
    {
        public int employee_liquidated_id { get; set; }
        public int sorted_concept_id { get; set; }
        public string concept { get; set; }
        public string quantity { get; set; }
        public Nullable<decimal> rem { get; set; }
        public Nullable<decimal> no_rem { get; set; }
        public Nullable<decimal> ded { get; set; }

        public virtual Employees_liquidated Employees_liquidated { get; set; }
    }
}
