//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using System;
    using System.Collections.Generic;

    public partial class Liquidation_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidation_types()
        {
            this.Liquidation_fixed_datas = new HashSet<Liquidation_fixed_datas>();
        }

        public int liquidation_type_id { get; set; }
        public string liquidation_type { get; set; }
        public string liquidation_type_initials { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidation_fixed_datas> Liquidation_fixed_datas { get; set; }
    }

    public partial class Liquidation_types
    {
        public string fullliquidationtype
        {
            get => liquidation_type_initials + " - " + liquidation_type;
        }
    }
}

