//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Schedules
    {
        public int calendar_id { get; set; }
        public int day { get; set; }
        public Nullable<int> turn_id { get; set; }
        public Nullable<int> fixed_schedule_id { get; set; }
        public string nwork_day { get; set; }

        public virtual Calendars Calendars { get; set; }
        public virtual Fixed_schedules Fixed_schedules { get; set; }
        public virtual Turns Turns { get; set; }
    }

    public partial class Schedules : ObservableObject
    {
        private string VerifyIsNull(string morning, string late)
        {
            return nwork_day == null ?
                (Turns?.morning + "\n" + Turns?.late) == "\n" ?
                (morning + "\n" + late) :
                (Turns?.morning + "\n" + Turns?.late) :
                nwork_day == "V" ?
                "VACACIONES" :
                "CUMPLEAÑOS";
        }

        public string Monday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_lu, Fixed_schedules?.late_lu);
        }
        public string Tuesday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_ma, Fixed_schedules?.late_ma);
        }
        public string Wednesday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_mi, Fixed_schedules?.late_mi);
        }
        public string Thursday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_ju, Fixed_schedules?.late_ju);
        }
        public string Friday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_vi, Fixed_schedules?.late_vi);
        }
        public string Saturday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_sa, Fixed_schedules?.late_sa);
        }
        public string Sunday
        {
            get => VerifyIsNull(Fixed_schedules?.morning_do, Fixed_schedules?.late_do);
        }

        public string color
        {
            get => nwork_day == null ?
                Turns?.color == null ?
                Fixed_schedules == null ?
                "#FFFFFFFF" :
                "#FFECEFF1" :
                Turns.color :
                nwork_day == "V" ?
                "#FFFFF59D" :
                "#FFC5E1A5";
        }

        private bool _holiday;
        public bool holiday
        {
            get => _holiday;
            set => Set(ref _holiday, value);
        }
    }

}

