//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Social_works : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Social_works()
        {
            this.Employees = new HashSet<Employees>();
        }

        public int social_work_id { get; set; }
        private string _social_work;
        public string social_work
        {
            get => _social_work;
            set => Set(ref _social_work, value);
        }
        public string street { get; set; }
        public Nullable<int> street_n { get; set; }
        public Nullable<int> floor { get; set; }
        public string departament { get; set; }
        public Nullable<int> province_id { get; set; }
        public string city { get; set; }
        public Nullable<int> postal_code { get; set; }
        public Nullable<long> phone_n { get; set; }
        public Nullable<decimal> percentage_retention { get; set; }
        public Nullable<decimal> amount_retention { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual Provinces Provinces { get; set; }
    }
}

