//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using GalaSoft.MvvmLight;
    using System;
    using System.Collections.Generic;

    public partial class Turns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turns()
        {
            this.Schedules = new HashSet<Schedules>();
        }

        public int turn_id { get; set; }
        public Nullable<System.TimeSpan> morning_d { get; set; }
        public Nullable<System.TimeSpan> morning_h { get; set; }
        public Nullable<System.TimeSpan> late_d { get; set; }
        public Nullable<System.TimeSpan> late_h { get; set; }
        public string color { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules> Schedules { get; set; }
    }

    public partial class Turns : ObservableObject
    {
        private string _morning;
        public string morning
        {
            get => morning_d?.ToString(@"h\:mm") + " - " + morning_h?.ToString(@"h\:mm");
            set => Set(ref _morning, value);
        }
        private string _late;
        public string late
        {
            get => late_d?.ToString(@"h\:mm") + " - " + late_h?.ToString(@"h\:mm");
            set => Set(ref _late, value);
        }
    }
}