//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using System;
    using System.Collections.Generic;

    public partial class Users
    {
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
    }

    public partial class Users
    {
        public string fullname
        {
            get => (last_name.Substring(0, 1) + ". " + name).ToUpper();
        }
    }
}